import type { KnowledgeTopic, KnowledgeRelationship } from '@/types/feed'

export const DEMO_TOPICS: KnowledgeTopic[] = [
  {
    id: 'positioning',
    title: 'Positioning',
    category: 'foundational',
    importance_score: 98,
    importance_level: 'essential',
    status: 'core',
    summary: 'Positioning defines how a company or product occupies a distinct, meaningful place in a customer\'s mind relative to alternatives. It is the strategic act of owning a specific definition in a competitive market.',
    frameworks: ['Category Design', 'Jobs To Be Done', 'Positioning Canvas', 'Value Proposition Design'],
    thinkers: ['April Dunford', 'Al Ries', 'Jack Trout', 'Geoffrey Moore'],
    debates: ['Is positioning becoming less important in an AI-first world where personalization replaces fixed messages?'],
    related_topics: ['Messaging', 'Brand Strategy', 'Demand Generation', 'Category Design'],
    frequently_confused_with: ['Messaging', 'Branding', 'Value Proposition', 'Differentiation'],
    recommended_reading: [
      { title: 'Obviously Awesome', author: 'April Dunford', type: 'book', url: 'https://www.amazon.com/Obviously-Awesome-Product-Positioning-Customers/dp/1999023005' },
      { title: 'Positioning: The Battle for Your Mind', author: 'Al Ries & Jack Trout', type: 'book', url: 'https://www.amazon.com/Positioning-Battle-Your-Mind/dp/0071373586' },
      { title: 'Crossing the Chasm', author: 'Geoffrey Moore', type: 'book', url: 'https://www.amazon.com/Crossing-Chasm-3rd-Disruptive-Mainstream/dp/0062292986' },
    ],
    content_angles: [
      'Beginner\'s Guide: What positioning actually means and why most companies get it wrong',
      'Executive Perspective: How weak positioning quietly kills revenue',
      'Contrarian Take: Why positioning is more important in an AI world, not less',
      'Framework Deep Dive: How to use the Positioning Canvas in practice',
      'Industry Application: Positioning for B2B SaaS vs. professional services',
    ],
    related_signal_topics: ['AI personalization', 'Brand strategy', 'Category creation'],
    trend_connections: ['Category design movement gaining traction in B2B'],
  },
  {
    id: 'demand-generation',
    title: 'Demand Generation',
    category: 'foundational',
    importance_score: 92,
    importance_level: 'essential',
    status: 'trending',
    summary: 'Demand generation is the process of creating awareness and interest in a company\'s products or services by educating the market about a problem they may not yet recognize, rather than capturing existing demand.',
    frameworks: ['Dark Funnel Marketing', 'Content-Led Growth', 'Thought Leadership Funnel', 'Pipeline Marketing'],
    thinkers: ['Chris Walker', 'Dave Gerhardt', 'Rand Fishkin'],
    debates: ['Should MQLs be replaced by demand generation metrics?', 'Is gated content killing demand gen programs?'],
    related_topics: ['Lead Generation', 'Content Marketing', 'Brand Marketing', 'Pipeline Marketing'],
    frequently_confused_with: ['Lead Generation', 'Inbound Marketing', 'Performance Marketing'],
    recommended_reading: [
      { title: 'Demand-Side Sales 101', author: 'Bob Moesta', type: 'book', url: 'https://www.amazon.com/Demand-Side-Sales-101-Customer-Journey/dp/1544509987' },
      { title: 'The Revenue Formula (podcast)', author: 'Mikkel Plaehn', type: 'podcast' },
      { title: 'Refine Labs State of Demand Gen Report', author: 'Chris Walker', type: 'research' },
    ],
    content_angles: [
      'Beginner\'s Guide: Demand gen vs. lead gen — the critical difference',
      'LinkedIn Post: Why the MQL is a broken metric for modern B2B',
      'Framework: How to build a demand gen function from scratch',
      'Contrarian Take: Gated content is destroying your demand generation',
      'Newsletter: The dark funnel — why buyers research you before you know they exist',
    ],
    related_signal_topics: ['B2B content marketing trends', 'Revenue operations', 'Pipeline acceleration'],
  },
  {
    id: 'category-design',
    title: 'Category Design',
    category: 'advanced',
    importance_score: 87,
    importance_level: 'important',
    status: 'trending',
    summary: 'Category design is the discipline of creating and defining a new market category — rather than competing in an existing one — so that your company becomes the de facto leader of a problem space you invented.',
    frameworks: ['The Niche Down Framework', 'POV-Led Selling', 'The Lightning Strike', 'Category Blueprint'],
    thinkers: ['Al Ramadan', 'Dave Peterson', 'Christopher Lochhead', 'April Dunford'],
    debates: ['Can category design work for smaller companies, or is it only for well-funded startups?'],
    related_topics: ['Positioning', 'Thought Leadership', 'Brand Strategy', 'Go-To-Market'],
    recommended_reading: [
      { title: 'Play Bigger', author: 'Al Ramadan, Dave Peterson, Christopher Lochhead, Kevin Maney', type: 'book', url: 'https://www.amazon.com/Play-Bigger-Dreamers-Innovators-Create/dp/0062407619' },
      { title: 'Niche Down', author: 'Christopher Lochhead & Heather Clancy', type: 'book' },
    ],
    content_angles: [
      'What category design actually means (and why it\'s not just branding)',
      'How to write a category point of view',
      'Case study: How [company] created a category and dominated it',
      'Contrarian: Category design is overused — here\'s when NOT to do it',
    ],
    related_signal_topics: ['Niche positioning', 'Thought leadership content'],
  },
  {
    id: 'incrementality-testing',
    title: 'Incrementality Testing',
    category: 'advanced',
    importance_score: 82,
    importance_level: 'specialized',
    status: 'core',
    summary: 'Incrementality testing measures the true causal impact of marketing activities by comparing outcomes between groups that received a treatment vs. those that did not — isolating what marketing actually caused versus what would have happened anyway.',
    frameworks: ['Holdout Testing', 'Geo-Based Experiments', 'Ghost Bidding', 'Media Mix Modeling'],
    thinkers: ['Jon Vaver', 'Jeff Greenfield', 'Cassie Kozyrkov'],
    debates: ['Is incrementality testing accessible to mid-market companies, or only enterprise?', 'Can you measure incrementality without a data science team?'],
    related_topics: ['Marketing Mix Modeling', 'Attribution', 'Experimentation', 'Media Measurement'],
    frequently_confused_with: ['Attribution', 'Marketing Mix Modeling', 'A/B Testing'],
    recommended_reading: [
      { title: 'Causal Inference: The Mixtape', author: 'Scott Cunningham', type: 'book', url: 'https://mixtape.scunning.com/' },
      { title: 'Meta\'s Robyn Documentation', author: 'Meta Marketing Science', type: 'research', url: 'https://robynmmm.com/' },
    ],
    content_angles: [
      'Plain language guide: What incrementality testing is and why it matters',
      'How to run a simple holdout test without a data science team',
      'The difference between attribution, MMM, and incrementality',
    ],
  },
  {
    id: 'ai-agents-marketing',
    title: 'AI Agents in Marketing',
    category: 'emerging',
    importance_score: 88,
    importance_level: 'emerging',
    status: 'trending',
    summary: 'AI agents are autonomous systems that can reason, plan, and take multi-step actions to complete marketing tasks — from research and content creation to campaign orchestration and customer interactions — with minimal human intervention.',
    frameworks: ['Agentic Workflows', 'Human-in-the-Loop AI', 'Tool Use Patterns', 'Retrieval-Augmented Generation'],
    thinkers: ['Andrew Ng', 'Harrison Chase', 'Ethan Mollick'],
    debates: ['Will AI agents replace marketing teams or augment them?', 'How do you maintain brand voice when AI handles content at scale?'],
    related_topics: ['Automation', 'Generative AI', 'Content Operations', 'Personalization at Scale'],
    recommended_reading: [
      { title: 'Co-Intelligence', author: 'Ethan Mollick', type: 'book', url: 'https://www.amazon.com/Co-Intelligence-Living-Working-Ethan-Mollick/dp/0593716744' },
      { title: 'Agentic AI explainer (a16z)', author: 'a16z', type: 'article', url: 'https://a16z.com/the-getting-started-guide-to-ai-agents/' },
    ],
    content_angles: [
      'What AI agents actually are — and what they\'re not',
      'How marketing teams are using AI agents today (with real examples)',
      'The ROI case for agentic marketing workflows',
      'The risks: where AI agents fail in marketing',
    ],
    related_signal_topics: ['AI automation', 'Generative AI for content', 'Marketing technology'],
    trend_connections: ['AI agent coverage up 340% in 48 hours'],
  },
  {
    id: 'synthetic-audiences',
    title: 'Synthetic Audiences',
    category: 'emerging',
    importance_score: 79,
    importance_level: 'emerging',
    status: 'emerging',
    summary: 'Synthetic audiences use AI to simulate how specific customer segments would respond to messaging, campaigns, or product concepts — enabling marketers to test ideas without real consumer research panels.',
    frameworks: ['Persona Simulation', 'AI Research Panels', 'Digital Twins for Marketing'],
    thinkers: ['Oded Netzer', 'Jonah Berger'],
    debates: ['Can synthetic audiences replace real consumer research?', 'Do simulated responses introduce systematic bias?'],
    related_topics: ['Market Research', 'Customer Segmentation', 'Personalization', 'AI Agents'],
    recommended_reading: [
      { title: 'Emerging Selves (Stanford research)', author: 'Stanford Digital Economy Lab', type: 'research' },
      { title: 'Using LLMs as synthetic respondents (HBR)', author: 'Various', type: 'article' },
    ],
    content_angles: [
      'What are synthetic audiences and why marketers are paying attention',
      'How to run a synthetic focus group using AI',
      'Limitations: What synthetic audiences can and can\'t replace',
    ],
    related_signal_topics: ['AI personalization', 'Customer research', 'Generative AI tools'],
  },
  {
    id: 'attribution-debate',
    title: 'Is Attribution Dead?',
    category: 'debate',
    importance_score: 90,
    importance_level: 'important',
    status: 'controversial',
    summary: 'Attribution — the practice of assigning credit to marketing touchpoints for conversions — has come under sustained critique as buyer journeys become more complex, privacy constraints limit tracking, and dark funnel activity grows. Experts disagree sharply on whether attribution should be abandoned or reformed.',
    frameworks: ['Multi-Touch Attribution', 'Last-Click Attribution', 'Data-Driven Attribution', 'Marketing Mix Modeling'],
    thinkers: ['Chris Walker', 'Avinash Kaushik', 'Jeff Greenfield', 'Les Binet'],
    debates: ['Should companies abandon MTA in favor of MMM?', 'Does attribution optimize for the measurable at the expense of the important?'],
    debate_for: [
      'Privacy regulations (iOS 14, GDPR) have made accurate touchpoint tracking impossible',
      'Attribution models optimize for the last measurable touchpoint, not actual cause',
      'The dark funnel (content, podcast, word of mouth) is invisible to attribution',
      'Companies that abandoned MTA and switched to revenue-based measurement grew faster',
    ],
    debate_against: [
      'Attribution, even imperfect, provides directional signal that improves decisions',
      'MMM is expensive and requires data science teams most companies don\'t have',
      'Without some attribution framework, marketing spend becomes unjustifiable to leadership',
      'New privacy-safe measurement tools (clean rooms, modeled conversions) are bridging the gap',
    ],
    related_topics: ['Incrementality Testing', 'Marketing Mix Modeling', 'Demand Generation', 'Dark Funnel'],
    frequently_confused_with: ['Incrementality Testing', 'Marketing Mix Modeling'],
    recommended_reading: [
      { title: 'How Brands Grow', author: 'Byron Sharp', type: 'book', url: 'https://www.amazon.com/How-Brands-Grow-What-Marketers/dp/0195573560' },
      { title: 'Refine Labs Attribution Research', author: 'Chris Walker', type: 'research' },
    ],
    content_angles: [
      'The case for abandoning attribution (and what to do instead)',
      'How to present marketing value without relying on attribution data',
      'A practical framework for measurement in a post-attribution world',
    ],
    related_signal_topics: ['Marketing measurement', 'Privacy-first analytics', 'Revenue operations'],
  },
  {
    id: 'april-dunford',
    title: 'April Dunford',
    category: 'thinker',
    importance_score: 95,
    importance_level: 'essential',
    status: 'core',
    summary: 'April Dunford is the world\'s foremost authority on product positioning for B2B technology companies. Former VP Marketing at 7 tech companies, she codified a systematic approach to positioning that has been adopted by thousands of companies globally.',
    frameworks: ['Obvious Awesome Positioning Framework', 'Competitive Alternatives Analysis', 'The Positioning Canvas'],
    thinkers: ['April Dunford'],
    debates: ['Is positioning a one-time exercise or an ongoing process?'],
    related_topics: ['Positioning', 'Category Design', 'Go-To-Market', 'Messaging'],
    recommended_reading: [
      { title: 'Obviously Awesome', author: 'April Dunford', type: 'book', url: 'https://www.amazon.com/Obviously-Awesome-Product-Positioning-Customers/dp/1999023005' },
      { title: 'Sales Pitch', author: 'April Dunford', type: 'book', url: 'https://www.amazon.com/Sales-Pitch-Better-Story-About/dp/1999023013' },
      { title: 'Positioning with April Dunford (podcast)', author: 'April Dunford', type: 'podcast' },
    ],
    content_angles: [
      'Key lessons from April Dunford\'s positioning framework',
      'How to apply the Obvious Awesome method to your own product',
      'April Dunford\'s framework for competitive alternatives — a guide',
      'What B2B founders get wrong about positioning (and how Dunford fixes it)',
    ],
  },
]

export const DEMO_RELATIONSHIPS: KnowledgeRelationship[] = [
  { source_topic_id: 'positioning', target_topic_id: 'category-design', relationship: 'related_to' },
  { source_topic_id: 'positioning', target_topic_id: 'demand-generation', relationship: 'related_to' },
  { source_topic_id: 'category-design', target_topic_id: 'positioning', relationship: 'extends' },
  { source_topic_id: 'demand-generation', target_topic_id: 'attribution-debate', relationship: 'related_to' },
  { source_topic_id: 'incrementality-testing', target_topic_id: 'attribution-debate', relationship: 'related_to' },
  { source_topic_id: 'ai-agents-marketing', target_topic_id: 'synthetic-audiences', relationship: 'related_to' },
  { source_topic_id: 'april-dunford', target_topic_id: 'positioning', relationship: 'extends' },
  { source_topic_id: 'april-dunford', target_topic_id: 'category-design', relationship: 'related_to' },
]
