// Design tokens for the GDELT Signal Feed.
// Scoped to feed components only — do not override global design system.
export const tokens = {
  colors: {
    navBackground: '#1a1560',
    primaryAction: '#1a1560',
    activeTabUnderline: '#1a1560',
    accent: '#4f46e5',
    bodyBackground: '#f8f8fb',
    cardBackground: '#ffffff',
    draftPanelBackground: '#fafafa',
    whyNowBackground: '#f0f0ff',
    tabBarBackground: '#ffffff',
    cardBorder: '#e5e7eb',
    tabBarBorder: '#e5e7eb',
    draftPanelBorderTop: '#e5e7eb',
    competitorFooterBorder: '#f3f4f6',
    whyNowBorderLeft: '#4f46e5',
    gdeltInfoIconBorder: '#9ca3af',
    tonePositiveBg: '#dcfce7',
    tonePositiveText: '#166534',
    toneNegativeBg: '#fee2e2',
    toneNegativeText: '#991b1b',
    toneNeutralBg: '#f3f4f6',
    toneNeutralText: '#6b7280',
    trendingBadgeBg: '#fef3c7',
    trendingBadgeText: '#92400e',
    unclaimedBadgeBg: '#f59e0b',
    unclaimedBadgeText: '#ffffff',
    inCirculationBadgeBg: '#6b7280',
    inCirculationBadgeText: '#ffffff',
    timeSensitiveBadgeBg: '#4f46e5',
    timeSensitiveBadgeText: '#ffffff',
    foundationContentBadgeBg: '#0d9488',
    foundationContentBadgeText: '#ffffff',
    momentumBarFill: '#1a1560',
    momentumBarTrack: '#e5e7eb',
    tooltipBackground: '#1a1a2e',
    tooltipText: '#ffffff',
    conceptSurfacedColor: '#4f46e5',
    gdeltBadgeBg: '#ede9fe',
    gdeltBadgeText: '#4f46e5',
    serviceTagBg: '#ede9fe',
    serviceTagText: '#5b21b6',
    signalAttrDot: '#4f46e5',
    sectionHeaderColor: '#9ca3af',
    competitorNameColor: '#1a1560',
    competitorHandleColor: '#9ca3af',
    gdeltInfoIconHover: '#4f46e5',
    generateButtonBg: '#1a1560',
    generateButtonActiveBg: '#374151',
    formatTabActiveBg: '#1a1560',
    formatTabActiveText: '#ffffff',
    tier1Badge: '#4f46e5',
    tier2Badge: '#0d9488',
    tier3Badge: '#9ca3af',
  },
  spacing: {
    feedMaxWidth: '780px',
    feedPaddingX: '16px',
    feedPaddingY: '24px',
    cardBodyPadding: '16px 18px',
  },
  borderRadius: {
    card: '4px',
  },
  boxShadow: {
    card: '0 1px 3px rgba(0,0,0,0.08)',
  },
  fontSize: {
    sectionHeader: '11px',
    gdeltBadge: '10px',
    tooltip: '11px',
    competitorHeadline: '14px',
    draftAngle: '12px',
    rationale: '11px',
  },
  letterSpacing: {
    sectionHeader: '0.8px',
    draftHeader: '0.5px',
  },
  dimensions: {
    momentumBarWidth: '80px',
    momentumBarHeight: '4px',
    gdeltInfoIconSize: '13px',
    signalAttrDotSize: '6px',
  },
  borders: {
    whyNowLeft: '2px solid #4f46e5',
    activeTabBottom: '2px solid #1a1560',
    tabBarBottom: '1px solid #e5e7eb',
  },
  tooltip: {
    gdeltMaxWidth: '220px',
    gapMaxWidth: '200px',
    timingMaxWidth: '210px',
    offsetBottom: 'calc(100% + 8px)',
  },
} as const
